
package com.yc.story.dao;

import com.yc.story.bean.StGoods;
import com.yc.story.bean.StGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    long countByExample(StGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    int deleteByExample(StGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    int insert(StGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    int insertSelective(StGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    List<StGoods> selectByExample(StGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    StGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") StGoods record, @Param("example") StGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    int updateByExample(@Param("record") StGoods record, @Param("example") StGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    int updateByPrimaryKeySelective(StGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_goods
     *
     * @mbg.generated Thu Aug 29 11:23:15 CST 2019
     */
    int updateByPrimaryKey(StGoods record);

}