package com.yc.story.dao;

import com.yc.story.bean.StNote;
import com.yc.story.bean.StNoteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    long countByExample(StNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    int deleteByExample(StNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    int insert(StNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    int insertSelective(StNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    List<StNote> selectByExample(StNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    StNote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") StNote record, @Param("example") StNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    int updateByExample(@Param("record") StNote record, @Param("example") StNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    int updateByPrimaryKeySelective(StNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    int updateByPrimaryKey(StNote record);
}