package com.yc.story.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StNoteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public StNoteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNTitelIsNull() {
            addCriterion("n_titel is null");
            return (Criteria) this;
        }

        public Criteria andNTitelIsNotNull() {
            addCriterion("n_titel is not null");
            return (Criteria) this;
        }

        public Criteria andNTitelEqualTo(String value) {
            addCriterion("n_titel =", value, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelNotEqualTo(String value) {
            addCriterion("n_titel <>", value, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelGreaterThan(String value) {
            addCriterion("n_titel >", value, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelGreaterThanOrEqualTo(String value) {
            addCriterion("n_titel >=", value, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelLessThan(String value) {
            addCriterion("n_titel <", value, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelLessThanOrEqualTo(String value) {
            addCriterion("n_titel <=", value, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelLike(String value) {
            addCriterion("n_titel like", value, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelNotLike(String value) {
            addCriterion("n_titel not like", value, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelIn(List<String> values) {
            addCriterion("n_titel in", values, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelNotIn(List<String> values) {
            addCriterion("n_titel not in", values, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelBetween(String value1, String value2) {
            addCriterion("n_titel between", value1, value2, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNTitelNotBetween(String value1, String value2) {
            addCriterion("n_titel not between", value1, value2, "nTitel");
            return (Criteria) this;
        }

        public Criteria andNContentIsNull() {
            addCriterion("n_content is null");
            return (Criteria) this;
        }

        public Criteria andNContentIsNotNull() {
            addCriterion("n_content is not null");
            return (Criteria) this;
        }

        public Criteria andNContentEqualTo(String value) {
            addCriterion("n_content =", value, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentNotEqualTo(String value) {
            addCriterion("n_content <>", value, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentGreaterThan(String value) {
            addCriterion("n_content >", value, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentGreaterThanOrEqualTo(String value) {
            addCriterion("n_content >=", value, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentLessThan(String value) {
            addCriterion("n_content <", value, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentLessThanOrEqualTo(String value) {
            addCriterion("n_content <=", value, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentLike(String value) {
            addCriterion("n_content like", value, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentNotLike(String value) {
            addCriterion("n_content not like", value, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentIn(List<String> values) {
            addCriterion("n_content in", values, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentNotIn(List<String> values) {
            addCriterion("n_content not in", values, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentBetween(String value1, String value2) {
            addCriterion("n_content between", value1, value2, "nContent");
            return (Criteria) this;
        }

        public Criteria andNContentNotBetween(String value1, String value2) {
            addCriterion("n_content not between", value1, value2, "nContent");
            return (Criteria) this;
        }

        public Criteria andNTimeIsNull() {
            addCriterion("n_time is null");
            return (Criteria) this;
        }

        public Criteria andNTimeIsNotNull() {
            addCriterion("n_time is not null");
            return (Criteria) this;
        }

        public Criteria andNTimeEqualTo(Date value) {
            addCriterion("n_time =", value, "nTime");
            return (Criteria) this;
        }

        public Criteria andNTimeNotEqualTo(Date value) {
            addCriterion("n_time <>", value, "nTime");
            return (Criteria) this;
        }

        public Criteria andNTimeGreaterThan(Date value) {
            addCriterion("n_time >", value, "nTime");
            return (Criteria) this;
        }

        public Criteria andNTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("n_time >=", value, "nTime");
            return (Criteria) this;
        }

        public Criteria andNTimeLessThan(Date value) {
            addCriterion("n_time <", value, "nTime");
            return (Criteria) this;
        }

        public Criteria andNTimeLessThanOrEqualTo(Date value) {
            addCriterion("n_time <=", value, "nTime");
            return (Criteria) this;
        }

        public Criteria andNTimeIn(List<Date> values) {
            addCriterion("n_time in", values, "nTime");
            return (Criteria) this;
        }

        public Criteria andNTimeNotIn(List<Date> values) {
            addCriterion("n_time not in", values, "nTime");
            return (Criteria) this;
        }

        public Criteria andNTimeBetween(Date value1, Date value2) {
            addCriterion("n_time between", value1, value2, "nTime");
            return (Criteria) this;
        }

        public Criteria andNTimeNotBetween(Date value1, Date value2) {
            addCriterion("n_time not between", value1, value2, "nTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table st_note
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 05 09:49:07 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table st_note
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}