package com.yc.story.bean;

import java.util.Date;

public class StNote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_note.id
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_note.n_titel
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    private String nTitel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_note.n_content
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    private String nContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column st_note.n_time
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    private Date nTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_note.id
     *
     * @return the value of st_note.id
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_note.id
     *
     * @param id the value for st_note.id
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_note.n_titel
     *
     * @return the value of st_note.n_titel
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public String getnTitel() {
        return nTitel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_note.n_titel
     *
     * @param nTitel the value for st_note.n_titel
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public void setnTitel(String nTitel) {
        this.nTitel = nTitel == null ? null : nTitel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_note.n_content
     *
     * @return the value of st_note.n_content
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public String getnContent() {
        return nContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_note.n_content
     *
     * @param nContent the value for st_note.n_content
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public void setnContent(String nContent) {
        this.nContent = nContent == null ? null : nContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column st_note.n_time
     *
     * @return the value of st_note.n_time
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public Date getnTime() {
        return nTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column st_note.n_time
     *
     * @param nTime the value for st_note.n_time
     *
     * @mbg.generated Thu Sep 05 09:49:07 CST 2019
     */
    public void setnTime(Date nTime) {
        this.nTime = nTime;
    }
}